#!/bin/sh
# Regenerates the built-in font: a small subset of Noto Sans Regular embedded
# into src/font_data.inc as a byte array.
#
# Usage: tools/make_font.sh path/to/NotoSans-Regular.ttf
# Needs fonttools (pyftsubset) and python3; with uv: uvx --from fonttools ...
set -eu

src=${1:?usage: $0 NotoSans-Regular.ttf}
root=$(cd "$(dirname "$0")/.." && pwd)
ttf=$root/third_party/font/NotoSans-subset.ttf

# ASCII, Latin-1, Greek, dashes, quotes, bullet, ellipsis, arrows and minus.
# (Noto Sans has no other math symbols such as <= or infinity; those are in
# Noto Sans Math.)
unicodes="U+0020-007E,U+00A0-00FF,U+0391-03A9,U+03B1-03C9,U+2013-2014,U+2018-201D,\
U+2022,U+2026,U+2191-2193,U+2212"

pyftsubset "$src" --unicodes="$unicodes" --layout-features=kern \
    --no-hinting --desubroutinize --output-file="$ttf"

python3 - "$ttf" "$root/src/font_data.inc" <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w") as out:
    out.write("// Generated by tools/make_font.sh from third_party/font/NotoSans-subset.ttf.\n")
    out.write("// Noto Sans, SIL Open Font License 1.1 (third_party/font/OFL.txt).\n")
    for i in range(0, len(data), 16):
        out.write(",".join(str(b) for b in data[i:i + 16]) + ",\n")
PY
